### ISSUE TITLE
make multi-factor authentication required for dsa aws buckets 

### ISSUE THREAD

**Issue by eaeslami** [cagov/data-infrastructure#115]
If possible, we would like MFA required (rather than optional) for all new and current users for the following five aae AWS buckets:

- aae-bppe-dev-us-west-2 
- aae-cdss-dev-us-west-2 
- aae-cdtfa-dev-us-west-2 
- aae-hcd-dev-us-west-2 
- aae-water-dev-us-west-2

This isn't urgent, but it would be ideal if this was done within the next week or two. If this isn't possible, could you provide us with a list of all current users with access to these five buckets so that we can confirm that they have MFA enabled.

Thanks!

**Comment by ian-r-rose** [comment]
@eaeslami I've been doing some more thinking and reading on this, and I think there probably is a way forward that would not be too onerous for data analysis projects, but would still require MFA (some resources linked in #128). It's not top of the priority list, but something we could probably do in the next few weeks.

**Comment by eaeslami** [comment]
interesting. yes, definitely not a top priority, but if we have time to discuss when you have more details that would be great!
