### ISSUE TITLE
Add notes about dbt testing & performance in docs

### ISSUE THREAD

**Issue by AeriShan-ODI** [cagov/data-infrastructure#140]
Want to include some notes on expectations for generic and singular testing, e.g. basic tests by default, maybe a link to some best practice guides, etc.

**Comment by AeriShan-ODI** [comment]
Performance part is done.

TODO: Will break this out into additions on testing and dbt project organization

**Comment by jkarpen** [comment]
Performance items are done. Aeri will create a new issue for follow-on work around dbt project organization.

**Comment by AeriShan-ODI** [comment]
Closing this as I've broken the remaining bits into #191 and #192
