### ISSUE TITLE
Gather feedback on training

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#142]
I (Britt) was thinking I could host an interview style session with calhr folks to gather feedback on each training module which would inform future MDSA trainings. 

I am happy to do it alone (which may be the safest format for CalHR folks to feel they can give honest feedback without the folks in the room with whom theyve done most of their trainings with). I am also happy to do it with Aeri as on the other hand their familiarity with them may solicit more honest feedback.

**Comment by britt-allen** [comment]
My next step on this would be to draft a questionnaire that we can use to guide the interview unless either of you have other thoughts on the best way forward? @jasonlally @AeriShan-ODI

**Comment by jasonlally** [comment]
I think drafting a questionnaire for the interview and sending around to the team is a great first step. We can briefly discuss at standup about whether @AeriShan-ODI should participate. I think it's fine you doing it from a more neutral standpoint.

Either way, drafting some questions would be great!

**Comment by AeriShan-ODI** [comment]
Agree with Jason's comment. I think a quick meeting with informal discussion might be helpful as an addition, if there is time. 
One of the things I'm most interested in is getting a sense of fitting & adapting the training to the needs of different levels of experience as well as different learning styles. E.g. I think John was frustrated with the training and I can relate - I also learn by just diving in and doing.
I don't need to be involved unless it's helpful but I'm definitely curious about the feedback :)

**Comment by britt-allen** [comment]
Planning to reach out to CalHR team thursday morning - please review and leave feedback before then. Otherwise I will move forward with scheduling a session to gather feedback based on what i have.

https://docs.google.com/document/d/1YCy3c_Gex6RDxt9GwGpMkIi6vxYyvqd-BijVZtLhj18/edit

cc: @ian-r-rose @AeriShan-ODI @jasonlally

**Comment by jasonlally** [comment]
@britt-allen - this looks good to me! @AeriShan-ODI did you take a look? Everything good?

**Comment by AeriShan-ODI** [comment]
Yes, forgot to comment mainly because it also looks good to me!

**Comment by jkarpen** [comment]
Action Item: @britt-allen to send Survey to Joel, Scott, Tiare and will schedule training feedback with John and Brian.
