### ISSUE TITLE
Update terraform role grants

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#143]
The terraform snowflake provider recently went through some painful churn and breaking changes due to some refactoring of role grants (cf. discussion [here](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1890)).
This has prevented upgrading to more recent versions with some bugfixes (e.g. https://github.com/cagov/data-infrastructure/pull/126#issue-1732889681).

The latest version of the provider introduces a new set of resources for role grants, with the old ones being deprecated. This will require updating the role grants here (and may require recreation of the roles all-together). But ultimately, it seems that the new structure will be more maintainable and easier to reason about.

**Comment by jkarpen** [comment]
@ian-r-rose planning to make this high priority when he returns, sprint 2024-20
