### ISSUE TITLE
Coalesce professional dev req

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#148]

**Comment by britt-allen** [comment]
@jasonlally can u paste gdoc link here, please?

**Comment by jasonlally** [comment]
Here it is: https://docs.google.com/document/d/1zV1iLvjkWM58yWUA9NMGK0zxbBE3EWuHx8mkdTclSJU/edit

**Comment by britt-allen** [comment]
This is done @jasonlally I mostly borrowed from our MDSCon justification, but made some changes/additions. Lmk if you have feedback or addtions.

**Comment by jasonlally** [comment]
Thank you @britt-allen - made some edits. You and @AeriShan-ODI can submit them in the form. Sorry for the bureaucracy! I wish I could submit for all 3 of us at once, but they need to update the process.

**Comment by britt-allen** [comment]
All done, @AeriShan-ODI can you mark this as done when you complete this?
