### ISSUE TITLE
DOF - ParcelQuest data discovery

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#151]
- [x] load data locally, splitting it into chunks because it is huge 
- [x] explore data
- [x] do some reading on ParcelQuest data

Notes from Fennis: I have uploaded that parcel dataset as a FGDB. Feature classes are sorted by County FIPS, with names like 'T_001_Parcels'. 

Link to data in Gdrive: https://drive.google.com/file/d/1bC2ELDukdC6os5NeE2OtOGyfs9DaF7rG/view?ts=65033894

**Comment by jkarpen** [comment]
Need a strategy for transferring a large file. Possibly Ian may create some AWS buckets for the transfer.

**Comment by jkarpen** [comment]
Britt will reach out to them and see if personal email method could work.

**Comment by britt-allen** [comment]
Emailed Fennis, they are out of the office until 9/14!

**Comment by britt-allen** [comment]
Received and downloaded parcel data from Fennis.

**Comment by britt-allen** [comment]
[] - load data locally, splitting it into chunks because it is huge 
[] - explore data
[] - do some reading on ParcelQuest data
[] - code snippets of useful utility functions that we build for on the fly merges to building footprint data 

@ian-r-rose

**Comment by britt-allen** [comment]
Notes for Britt's own learning:

- ParcelQuest is the sole provider of California County Assessor property data from all 58 California counties
- ParcelQuest receives daily updated data directly from California county departments. 

https://www.parcelquest.com/faqs/
https://www.esri.com/partners/parcelquest-a2T5x000006aecHEAQ
