### ISSUE TITLE
DOF - Discovery on overlapping footprints

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#155]
For footprints that overlap more than one geography (like more than one census tract) - how would they want us to handle this? Show up in both, assign to one or the other dependent on some decisioning (like which its more in)?

**Comment by jasonlally** [comment]
@ian-r-rose - no rush on this, but when you do have something figured out, I think this would be a fun thing to walk through with the full data services and engineering team.

**Comment by ian-r-rose** [comment]
> @ian-r-rose - no rush on this, but when you do have something figured out, I think this would be a fun thing to walk through with the full data services and engineering team.

Yeah! I have some prototypes in Python, but it will be fun to do in Snowflake. My intuition about how snowflake works suggests that the naive way of doing it would be quite slow, but some careful reasoning about partitioning can solve it. But that isn't necessarily true, and it will be fun to test.

**Comment by britt-allen** [comment]
This is linked to #175
