### ISSUE TITLE
DOF - Implementation of dbt models

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#156]
- [x] Overlapping footprints #175 #178 #190 
- [ ] ~~Data updates that preserve historical ones~~
- [x] Data enrichment (joins to other datasets) #168 #182 #189

**Comment by jkarpen** [comment]
@britt-allen can you link the relevant issues to this?

**Comment by ian-r-rose** [comment]
Closing as complete, updates incorporating historical edits will be handled using a local workflow
