### ISSUE TITLE
DOF - Develop presentation

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#160]
Develop presentation on:
- Analysis-ready footprint dataset
- Workflows for joining with parcels datasets (or other geospatial datasets)
- Workflows for removing known “bad” footprints

Reference: [Notes - Socializing DOF Project Call 1/4/24](https://docs.google.com/document/d/1A58JU9ogy6gO5xVI-vA6KLvOY0QSTHWEO7Ew7hqtNBk/edit?pli=1)

**Comment by britt-allen** [comment]
Let's build off of what Fennis has put together unless you've been developing elsewhere? @ian-r-rose

**Comment by britt-allen** [comment]
I added Fennis' slides to our drive: https://drive.google.com/drive/folders/1zOvupHvxX8XBtzxfv-W-ywy3TmZw7D3f

**Comment by jasonlally** [comment]
@ian-r-rose @britt-allen Can we adapt the content into the ODI template? We can do a check with Fennis so there are no surprises there.

Also, do you want to put some time on my calendar to do a run through/feedback session?

**Comment by britt-allen** [comment]
We also have our GIS CoP User Research on Building Footprint Data slides for inspo: https://docs.google.com/presentation/d/1bcHANN6hw_d21wxGaNQLlvfglQlX_i-OjdMaLBTGXBc/edit#slide=id.gd01156d741_1_3 @ian-r-rose

**Comment by ian-r-rose** [comment]
Closing as complete, thanks all
