### ISSUE TITLE
Add to project management pain points document

### ISSUE THREAD

**Issue by jasonlally** [cagov/data-infrastructure#165]
Take a look at the pain points document and add things that have been challenging or not working as well for you from a project management perspective: https://docs.google.com/document/d/1iLHXvQWnPxinlg7ujsu1yfMAWMBeat_VIY4fBgJLNpE/edit 

This will be an input into discussing and prioritizing pain points we want to fix through improvements to process, templates, etc.

**Comment by jasonlally** [comment]
@AeriShan-ODI @ian-r-rose @britt-allen - can you add your comments by end of day Thursday, Aug 3rd?

**Comment by britt-allen** [comment]
Done

**Comment by ian-r-rose** [comment]
Added a couple of things, I think the list is pretty good

**Comment by jasonlally** [comment]
@AeriShan-ODI - did you have a chance to review the pain points document?
