### ISSUE TITLE
Set up Fivetran Platform Connector & Dashboard

### ISSUE THREAD

**Issue by AeriShan-ODI** [cagov/data-infrastructure#167]
Now that Fivetran is deprecating audit tables and has made MAR for it free, we might consider using their [Platform Connector](https://fivetran.com/docs/logs/fivetran-platform?mkt_tok=MzUzLVVUQi00NDQAAAGNb3_V-vp3DmNnbr2dLstk7ZmbJO7iMICj6YpvmxNkb0T_at-itJGQSFYFHImLuIktMq7E2r4CFs1YNYVBm-E7PW_U7OaQMyxdMpVpk6yidTHP) and building some basic reporting using PowerBI (with or without their [dbt package](https://fivetran.com/docs/transformations/data-models/fivetran-platform-connector-data-model?mkt_tok=MzUzLVVUQi00NDQAAAGNb3_V-okeFnAD2cJZT4gj7S6Y5oc9iwd8WXDi6_8jespR6hpQIkak0wX0gql1Y1Rs9m6wS9qkppBI4HPNVCnIEfTBZ5p0fbNpFmKEgjhbQeC1)). The goal being to get us better at PowerBI and to build something useful that will help us monitor granular Fivetran usage data for projects.

**Comment by jkarpen** [comment]
Closing this and tracking in a new issue.
