### ISSUE TITLE
Change location of where marts data is landing

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#179]
This is for our dev environment, currently this is landing in the Analytics schema.
The configuration is not hard, but we need to discuss logic. We can mirror what we've been doing in the CalHR repo: https://github.com/cagov/caldata-mdsa-calhr-ecos/blob/main/transform/dbt_project.yml

**Comment by britt-allen** [comment]
Related reading for britt: https://docs.getdbt.com/docs/build/custom-schemas#:~:text=How%20does%20dbt%20generate%20a,model%20should%20be%20built%20in.

**Comment by britt-allen** [comment]
@ian-r-rose add anything else if you can find it

**Comment by ian-r-rose** [comment]
Closing as completed by #251
