### ISSUE TITLE
Investigate Approach to Remote Pairing

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#181]
Notes below come from Slack thread on this topic https://cadotgov.slack.com/archives/C04A487ES5U/p1691179036168859

From Ian:
VS Code: https://code.visualstudio.com/learn/collaboration/live-share
Real time collaboration with JupyterLab (and an appearance by yours truly from six years ago): https://blog.jupyter.org/how-we-made-jupyter-notebooks-collaborative-with-yjs-b8dff6a9d8af

From Blake:
maybe reach out to engineering as well.  they could have good insights
(Ian reached out to Engineering here): https://cadotgov.slack.com/archives/CR76CJSDB/p1691177141940439
**From Ian convo with Chach:**
"To Jon’s point - code pairing often explodes along the fault lines of developers securities and insecurities.
I’ve only heard of pairing sounding like it went well in code camps scenarios, never at work or on a time driven project.
My projects where it went well were all art projects or volunteer projects.
Interested in understanding how to facilitate it so it goes well, but think the insecurity factor is not to be underestimated."

From Jason: 
https://www.coscreen.co/
https://www.coscreen.co/blog/top-8-remote-pair-programming-tools/

**Comment by britt-allen** [comment]
@ian-r-rose and I tested **Live Share** today on issue #182. It was easy to set up and for Ian to get in there. I didn't experience any lags and the process overall was pretty intuitive.

**Comment by jkarpen** [comment]
Team feels Live Share (extension for VS Code) is a good tool for this need.
