### ISSUE TITLE
dbt Documentation on Project Organization & Best Practices

### ISSUE THREAD

**Issue by AeriShan-ODI** [cagov/data-infrastructure#192]
This is to add notes to the dbt docs on how we approach project organization. I'd started this but got hung up on applicability of my own previous approaches and felt it was worth waiting to see how CalHR adapted to the Fishtown approach. That's worked well for them and I think we should standardize on that but with some caveats and minor modifications.

**Comment by britt-allen** [comment]
I believe this issue can be closed or deleted @jkarpen

**Comment by jkarpen** [comment]
Closing as this is no longer needed
