### ISSUE TITLE
Ingest Snowflake logs into Sentinel

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#196]
We have our own Sentinel account at ODI for capturing system logs. Snowflake logs should be configured to be sent to that system.

@kevinVodi can you share the documentation you found for this? As part of configuring it for an account, we should document the steps and time commitment.

**Comment by kevinVodi** [comment]
@ian-r-rose Here is the link re: SnowFlake + Sentinel: https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/snowflake-using-azure-function

**Comment by ian-r-rose** [comment]
Thanks @kevinVodi

**Comment by ian-r-rose** [comment]
@kevinVodi @ChadABratton Do you have any updates on when a good time would be to set up Sentinel logging for our Snowflake org? Since we have a number of sub-accounts which need independent logging, it would be best if we could set up a repeatable pattern so that our team could add new log streams as needed.

**Comment by ian-r-rose** [comment]
@kevinVodi and I met with CDT today, and we successfully set up logging ingestion for our primary Snowflake account. Once #228 is in, I can propagate those changes to our other accounts (probably next week)

**Comment by kevinVodi** [comment]
Hi @ian-r-rose - feel free to book a time with me to proceed with the remaining Snowflake instances for sentinel log ingestion. Here's my calendly: https://calendly.com/kevin-vellanoweth-odi

**Comment by ian-r-rose** [comment]
Hi @kevinVodi we have a new platform engineer joining next week, and it occurred to me that this could be a good onboarding task. Would it be okay to hold on this for a week or two?

**Comment by kevinVodi** [comment]
No rush on my end!
--
Kevin

**Comment by kevinVodi** [comment]
How can IT assist?

**Comment by ian-r-rose** [comment]
@kevinVodi can you, me, and @melanie-logan meet to catch Melanie up on what we've done here to date and talk about next steps?

**Comment by kevinVodi** [comment]
Sounds good - here's my calendly: https://calendly.com/kevin-vellanoweth-odi

**Comment by ian-r-rose** [comment]
Closing as complete
