### ISSUE TITLE
Org administration follow-ups for Snowflake professional services

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#198]
We had a few questions about org administration that would be good to ask Snowflake professional services about:

- Is there a way to configure Sentinel logging at the org level, or must it be done individually across all accounts? (It seems like the latter is probably the case)
- Is there any way to automatically create an IT administrator (or set of them) for each account, or must it be done individually? (again, it seems like the latter)
- Is it possible to have external users with username/password auth at the same time as SSO+SCIM in an account? i.e., if we mostly use Okta SCIM for our team, but want to invite external collaborators to the account, does that present any difficulties?

**Comment by jasonlally** [comment]
Just to close this loop finally:

1. No way to configure Sentinel logging at the org level
2. No way to automatically create an IT admin for each account
3. I'm pretty sure the way we need to provision users with Okta is to add them through Okta - this is something I want to probe with IT-Ops in terms of operational overhead and processes. The CDTFA project won't require external users (at least initially) so we can use this integration to work out these edges
