### ISSUE TITLE
Investigate GitHub codespaces as a serverless hosted coding environment

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#203]
GitHub codespaces can be configured to spin up ephemeral development environments, including using VS Code and JupyterLab. This could be a useful thing to deploy for people who are uncomfortable setting up python environments themselves.

This issue is to do a bit of experimentation with codespaces to see how well it would work for this use case, including:

* dbt workflows
* python GIS workflows
* docs authoring (?)

If it works well, it could be a nice thing to include in our infrastructure template.

**Comment by jkarpen** [comment]
@AeriShan-ODI will help testing this out with existing PR.
