### ISSUE TITLE
Discuss Internal training on Github for Operations side

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#206]
Anne would like us, DSE, to host a training for the operations side. We can choose whatever format we'd like, currently we do our GitHub training async. She's targeting last week of October. Need approval from @jasonlally and wanted to generally discuss with the broader team.

**Comment by jasonlally** [comment]
I just realized I never responded to this! I'm generally good with this just want to make sure we can fit into our workload. Do we know what kinds of things they'd want to learn?

We can discuss at a future standup as a team too.

**Comment by jasonlally** [comment]
@britt-allen - do we want to pick this up this year? I know Annie's got a couple of trainings cooking around HCD so the priority may have shifted.

**Comment by britt-allen** [comment]
Yeah maybe we can target March or April? I want to see how the new refinements we make to our GH training with Caltrans first!

**Comment by jasonlally** [comment]
I'm going to assign to you and backlog it and put a due date in late March just as a tickler to revisit then

**Comment by britt-allen** [comment]
Operations team is no longer on GitHub so this is no longer relevant.
