### ISSUE TITLE
Explore new file formats for ESRI

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#214]
We need to review other formats for arcgis pane catalog view to enable @fennisreed's workflow there. 

Currently looking into KMZ or OSMPBF

https://www.esri.com/en-us/arcgis/products/arcgis-data-interoperability/supported-formats

Look into driver support, if we can get one or both to work we'll upload a sample with Alpine County

**Comment by ian-r-rose** [comment]
The goal here has been to find a way to use ArcGIS Pro's data catalog pane, which allows for drag and drop usage of some geospatial file formats. That catalog pane allows connections to cloud storage (cool!) but it seems that the formats supported in cloud storage are very limited (possibly nothing?!). Things we have tried:

- Zipped shapefile
- Unzipped shapefile
- KMZ
- Unzipped file geodatabase
- geoparquet

Note: Several of these still work if they are downloaded first. But they seem to struggle when loaded directly from cloud storage. @fennisreed am I missing anything?

**Comment by ian-r-rose** [comment]
We've done some rounds with Esri support, and it seems like the Cloud Storage integration for the catalog pane only supports raster tile files, not general purpose vector geospatial datasets: https://community.esri.com/t5/arcgis-pro-questions/amazon-cloud-storage-connection-doesn-t-display/td-p/408228

We're going to abandon this investigation for the time being: people can still download the files and work with them in ArcGIS Pro, but it seems the catalog pane will not work.
