### ISSUE TITLE
DOF - Establish local workflow for flagging and removing "bad" building footprints

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#220]
This should be able to take a footprints dataset as well as a dataset of known "bad" footprints (fields, lawns, roads, etc), and filter out the bad ones from the primary dataset. It should be robust to updates in the source dataset (i.e., as MS pushes changes)

The known bad dataset is expected to be small, and could be stored on a local hard drive or in GitHub.

**Comment by ian-r-rose** [comment]
cc @fennisreed for visibility

**Comment by fennisreed** [comment]
For test cases of bad features, I recommend using San Bernardino (071) from the global dataset, which has a good number of errors of inclusion. These locations could be stored in a csv with coordinates for randomly selected internal points. A spatial filter on later versions using these points would allow easy exclusion without needing to replicate a primary key between MS GLOBAL versions.

[GLOBAL_071_Exclude.csv](https://github.com/cagov/data-infrastructure/files/13034229/GLOBAL_071_Exclude.csv)

**Comment by britt-allen** [comment]
Write a function that can use a geometric comparison to drop matching geometries of bad footprints.

**Comment by britt-allen** [comment]
Morning @ian-r-rose, I am finished with the bad footprint code and would like your review! https://gist.github.com/britt-allen/8930c8b799c1d35dbd1845a917aa19a5

**Comment by ian-r-rose** [comment]
Thanks @britt-allen. I know that @mbobra and company are looking into notebook reviewing tools (my knowledge there is a bit out of date). But for the time being I'll just add some review notes here:

1. I don't think we need a cell repr-ing `footprints.shape`
2. There are a few places where you have one-line (or very few line) functions that do dataframe operations, and then are only used once (or very few times). I'd recommend removing the functions and just demonstrate how to do the dataframe operations directly. (this includes `top_n_largest_footprints` `explore_footprints` and `save_geodataframe_to_file`)
3. I'm not sure the intention of `save_bad_footprints_as_geodf()`, but it doesn't really save anything, and isn't used elsewhere. If we want to demonstrate how to save a list of bad footprints to a file, perhaps a one-line example would suffice:
    ```python
    footprints_df[bad_footprint_indexes_list][["geometry"]].to_file("bad_footprints.geojson")
    ```
1. I think your code for `geom_equals` and `equals_exact` does not work (this is the cause of all the `UserWarning`s you see). They are differently indexed dataframes, running `df1.geometry.equals_exact(df2)` will have unexpected results as it's a row-wise operation rather than a merge/join.
2. I'm not sure that the `drop_duplicates` approach works as you intend: I think it drops the second copy of the geometry, but not both of them (which is what we want)

**Comment by ian-r-rose** [comment]
I should note: I think the approach for options 3 and 4 works, it's the logic for `matching_geoms` that I think has some issues with the index. It may work to just remove that line all-together and just do the merge directly on `bad_geometries`

**Comment by britt-allen** [comment]
> Thanks @britt-allen. I know that @mbobra and company are looking into notebook reviewing tools (my knowledge there is a bit out of date). But for the time being I'll just add some review notes here:
> 
> 1. I don't think we need a cell repr-ing `footprints.shape`
This is a visual check to see how many rows we start with and I think is a harmless cell and helpful for the user to reference to see if the code they run later removes the amount of bad footprints expected. Wdytat?
> 2. There are a few places where you have one-line (or very few line) functions that do dataframe operations, and then are only used once (or very few times). I'd recommend removing the functions and just demonstrate how to do the dataframe operations directly. (this includes `top_n_largest_footprints` `explore_footprints` and `save_geodataframe_to_file`)
Why do you recommend that? Can you explain further on this preference?
> 3. I'm not sure the intention of `save_bad_footprints_as_geodf()`, but it doesn't really save anything, and isn't used elsewhere. If we want to demonstrate how to save a list of bad footprints to a file, perhaps a one-line example would suffice:
>    ```python
>    footprints_df[bad_footprint_indexes_list][["geometry"]].to_file("bad_footprints.geojson")
>    ```
Semantics aside, the `save_bad_footprints_as_geodf()` is used elsewhere. It is used in the very next function. The intention of this function is to take was is otherwise a Python list type of indexes and transfer them, along with their corresponding geometries, to a geopandas dataframe so we have a compatible type to work with in following operations.
> 4. I think your code for `geom_equals` and `equals_exact` does not work (this is the cause of all the `UserWarning`s you see). They are differently indexed dataframes, running `df1.geometry.equals_exact(df2)` will have unexpected results as it's a row-wise operation rather than a merge/join.
Makes sense and you're right! I forgot those were row-wise operations.
> 5. ~I'm not sure that the `drop_duplicates` approach works as you intend: I think it drops the second copy of the geometry, but not both of them (which is what we want)~ Update: never mind, I see the `keep=False` now! It was cut off in the rendering of the gist in github.
🫡

New code is live at the same link and ready for your review @ian-r-rose: https://gist.github.com/britt-allen/8930c8b799c1d35dbd1845a917aa19a5

**Comment by ian-r-rose** [comment]
Thanks @britt-allen, this is looking close. I'll try to respond to some of your questions here, and follow up with some code review notes:

> > 1. I don't think we need a cell repr-ing `footprints.shape`
> 
> This is a visual check to see how many rows we start with and I think is a harmless cell and helpful for the user to reference to see if the code they run later removes the amount of bad footprints expected. Wdytat?
> 

Sure, no objection.

> > 2. There are a few places where you have one-line (or very few line) functions that do dataframe operations, and then are only used once (or very few times). I'd recommend removing the functions and just demonstrate how to do the dataframe operations directly. (this includes `top_n_largest_footprints` `explore_footprints` and `save_geodataframe_to_file`)
> 
> Why do you recommend that? Can you explain further on this preference?
> 

This gets into API design questions, and there are a lot of considerations that go into that. I'll try to summarize my thinking. Organizing code into functions involves a few goals:
1. Reducing duplication/enabling reuse
2. Generalizing logic
3. Encapsulating complex logic so you can expose a simplified interfaces

As an example, I don't `top_n_largest_footprints` accomplished those goals. It wasn't used in more than one place in a workflow, so didn't accomplish code reuse. It also wasn't particularly general (i.e., it assumed that the df had a column named `"area_sqm"`), which limits the number of dataframes that could be fed into it. Finally, it didn't really provide much simplification or encapsulation: the one line of code inside the function was roughly as complex as actually using the function.

For those reasons, I think that it's better to just show example snippets of how to pull out, e.g., the top 100 largest footprints, rather than write a bespoke function to do that.

> > 3. I'm not sure the intention of `save_bad_footprints_as_geodf()`, but it doesn't really save anything, and isn't used elsewhere. If we want to demonstrate how to save a list of bad footprints to a file, perhaps a one-line example would suffice:
> >    ```python
> >    footprints_df[bad_footprint_indexes_list][["geometry"]].to_file("bad_footprints.geojson")
> >    ```
> 
> Semantics aside, the `save_bad_footprints_as_geodf()` is used elsewhere. It is used in the very next function. The intention of this function is to take what is otherwise a Python list type of indexes and transfer them, along with their corresponding geometries, to a geopandas dataframe so we have a compatible type to work with in following operations.
> 

I'm not convinced that it's necessarily better to have it as a function as opposed to cell with an example snippet (for a lot of the same reasons as outlined above), but if you want to emphasize that this is one possible workflow for creating a dataframe with "bad" footprints, I don't object.

I expect that in practice Fennis may use some other workflow for finding bad footprints, so we want to be as general as possible in the `remove_bad_footprints` function.

**Comment by ian-r-rose** [comment]
Some notes from code review:

**`bad_footprints_to_geodf`**: 

Whether or not it is a function, I'm a bit uncomfortable keeping the index values from the original dataframe: we want this to work regardless of whether the two dataframes have the same index numbering. The previous version of this gist had some *accidental* matches with `geom_equals` because the indexes were aligned, but we shouldn't rely on that in general. What do you think about *not* including the old index values in the resulting "bad footprints" dataframe?

**`remove_bad_footprints`**:

I did some testing of this with the following assertion:
```python
assert not geopandas.GeoDataFrame(clean_footprints).geom_equals(bad_footprints_df.iloc[0].geometry).any()
```
Some notes:
1. Since you are doing the work to evaluate multiple approaches to filtering the bad footprints, and there may be some situations where different ones are appropriate, what if we expose the different approaches through an argument to the function with a sensible default? Then the function could have an `if`/`elif` block dispatching to the various approaches.
1. I noticed that the `set_index()` approach wasn't working in my testing: the resulting frame had the same number of rows as the starting one.
1. It seems that the `set_index()` approach lost its "geodataframe"-ness. Probably geopandas doesn't envision a geometry as an index rather than a column. We probably need to re-coerce to a geodataframe with this approach.
1. I wasn't able to reproduce the timings of these: the first two approaches took considerably more time than what you note in your comments. Is it possible you were testing on a smaller subset?
1. Option 3 looks good to me.
1. I see there is no longer an option with spatially aware functions `geom_equals` or `equals_exact`. Did you have any luck with those? FWIW I'd expect it to be an extremely expensive operation (probably requires a cross join), so it may not be worth recommending.

**On saving the resulting files**:

I noticed that the shapefile output was not zipped. Probably the easiest way forward is to use the `.shz` extension, as we did in the write-to-s3 job.

**Comment by fennisreed** [comment]
Pursuant to our discussion yesterday afternoon, I've added a GeoJSON with a small sample of erroneous footprints from San Bernardino. Future errors of inclusion will be appended to this feature.

https://gist.github.com/fennisreed/d7cd238a92c197b5117581caa03317ae

**Comment by ian-r-rose** [comment]
Thanks @fennisreed!

We've put together a new gist that demonstrates a workflow for removing the errors of inclusion [here](). It uses your GeoJSON with the San Bernardino County footprints data.

The main function is `remove_matching_geometries`, which takes the two geodataframes and does the removal operation. It supports three strategies:

1. Almost equal geometries (spatially aware)
2. Exactly equal geometries (spatially aware)
3. Geometries with the same numeric values (not spatially aware)

Usage looks like:

```python
good_footprints = remove_matching_geometries(
    footprints,
    bad_footprints,
    strategy="geom_almost_equals",
    decimal=6,
)
```

After a bit of experimentation, I think in most cases you'll want the first option (which I've set as default). Floating point number comparisons are famously fraught, so having a bit of tolerance for not-exactly-equal numbers is usually a good thing, even for geometries that are effectively identical. For instance, the mere operation of outputting to geojson and then reading it back in again resulted in a small amount of lost precision in the footprints which made the "exactly equal" checks fail, even for the same footprints.

That said, there may be some circumstances where you want more precise checks, so those are available as well! There is also a tuning parameter for decimals of precision with the almost-equals check.

Let us know how this works for your use case!

**Comment by fennisreed** [comment]
Hello Ian and Britt! 

I had the chance to test out this script this morning - it works great and considerably faster than the spatial comparison I was using previously. I've baked it into an updated ArcToolbox and a brief one-pager to describe the ArcPro content. Could you add these to the html page?

[AccessFootprintsArcPro.pdf](https://github.com/cagov/data-infrastructure/files/13590918/AccessFootprintsArcPro.pdf)
[Download MS Global Footprints.zip](https://github.com/cagov/data-infrastructure/files/13590933/Download.MS.Global.Footprints.zip)

Thanks, and looking forward to chatting this afternoon!

**Comment by fennisreed** [comment]
While the script runs great, it does produce the following error message, which may mean a minor revision is necessary.

> [58]:68: FutureWarning: The 'geom_almost_equals()' method is deprecated because the name is confusing. The 'geom_equals_exact()' method should be used instead.

**Comment by ian-r-rose** [comment]
I'm going to close this issue as complete, thanks for all the hard work on this @britt-allen and @fennisreed!
