### ISSUE TITLE
Create `.atbx` file for ArcGIS Pro users to be able to more easily work with footprints

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#223]
@fennisreed will take point on this.

**Comment by ian-r-rose** [comment]
Fennis shared a demo of this today, it was cool! @fennisreed, when you feel it is complete, would you mind sharing it here? We could consider distributing it with the repo

**Comment by fennisreed** [comment]
Hi Ian,

I've attached the current version of the .atbx file. Further options to be added once we've determined the best way to remove errors of exclusion from the download.

[Download MS Global Footprints.zip](https://github.com/cagov/data-infrastructure/files/13192445/Download.MS.Global.Footprints.zip)

**Comment by ian-r-rose** [comment]
Thanks @fennisreed. We can distribute this as a static file alongside the Data URLs. Does that seem reasonable to you?

**Comment by fennisreed** [comment]
Sounds great to me!
