### ISSUE TITLE
Run GlobalML building footprints pipeline on a schedule

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#224]
We are currently running a scheduled Airflow job for the US building footprints dataset, but not the more-frequently-updated GlobalML building footprints dataset.

**Comment by britt-allen** [comment]
Hey Ian, I see I am assigned to this, but was under the impression you were leading this effort. Did you assign me for review purposes only or am I missing something?

**Comment by ian-r-rose** [comment]
I just defaulted to "pairing" on things, but this is one I can drive

**Comment by britt-allen** [comment]
That makes sense, always happy to "pair" and learn from you, but also don't want to slow down any progress. I already have a lot to learn from my own issues. 😅
