### ISSUE TITLE
DOF - Schedule ODI Lunch and Learn

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#262]
- [x] Schedule Lunch and Learn with Fennis and Caldata team
- [x] Invite rest of ODI
- [x] Invite Katie's team

Reference: [Notes - Socializing DOF Project Call 1/4/24](https://docs.google.com/document/d/1A58JU9ogy6gO5xVI-vA6KLvOY0QSTHWEO7Ew7hqtNBk/edit?pli=1)

**Comment by britt-allen** [comment]
@ian-r-rose I am assigning this to you since you're taking the lead on reaching out to Fennis. Can you add in the rest of the issue details and can you also let me know if/how I can be useful in the process aside from actually presenting, please?

**Comment by jasonlally** [comment]
Here are the emails for Katie's team:

"Wong, Anneli@CIO" <anneli.wong@state.ca.gov>, "Regan, Katie@CIO" <katie.regan@state.ca.gov>, "Petrik, Lothar@CIO" <lothar.petrik@state.ca.gov>, louie.rowley@state.ca.gov, "Hayashi, Sam@CIO" <sam.hayashi@state.ca.gov>

@ian-r-rose - feel free to reach out to Katie to let her know we're scheduling the lunch and learn and would like to invite her team. You can verify that these are the right people as well.

**Comment by ian-r-rose** [comment]
Thanks!

**Comment by ian-r-rose** [comment]
Closing as complete
