### ISSUE TITLE
Meta-Issue: DOF - Develop project communication materials

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#265]
- [x] Case study #293
- [x] Blog post

**Comment by britt-allen** [comment]
@jasonlally can you link to the case study template here please?

**Comment by jasonlally** [comment]
@britt-allen, here's the case study [template](https://docs.google.com/document/d/1qqJIX0ltO1Mtr6Jm3V2-94d2A7taMc3EWVvLQTUhm3s/edit)

And here are the examples from AAE projects:
- [Case Study: Forecasting Community Water System Outages](https://docs.google.com/document/d/1pBRZpTwBnqncAvpgozHnhMYHXs68U-lrw5PtOLFV60Y/edit#heading=h.59mnf2h5pbto)
- [Case Study: Building Housing Intelligence for California](https://docs.google.com/document/d/1asmpGHPeQnB6ySy1i5Mzo5aXH8k3JvxzEEbZFuioTtU/edit#heading=h.59mnf2h5pbto)

**Comment by britt-allen** [comment]
Have you started a draft for either of these @ian-r-rose? If so, can you link me to it, please? If not, I can get them started.

**Comment by ian-r-rose** [comment]
No, I've started for CalHR, but not DOF. Feel free to get started!

**Comment by jkarpen** [comment]
From Sprint Planning discussion: Case study is the higher priority for now, the blog post can come after the survey has gone out (1-2 weeks after).

**Comment by ian-r-rose** [comment]
Closing, as the draft is complete and out for review. Follow-on work will be tracked in new issues
