### ISSUE TITLE
Make GitHub norms document accessible to stakeholders

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#270]
Goal for this issue is to update the Github Norms document and place it somewhere accessible to our MDSA project stakeholders. (Ideally in the project docs here https://cagov.github.io/data-infrastructure/)

- [ ] Cleanup norms doc, add a checklist for users to look at when creating a new issue (TLDR version)
- [ ] Move the document into our Docs pages

**Comment by britt-allen** [comment]
This may be a helpful guide to pull from: https://docs.google.com/document/d/1mv-0hymSr2WIUgE-9l6P53M44Fd13nQ_QUpgxSIgKTU/edit

**Comment by jkarpen** [comment]
@jkarpen add link to the GitHub Norms doc for reference.

**Comment by jkarpen** [comment]
Here is the GitHub Guidelines doc from earlier this year that we want to bring into the project docs. https://docs.google.com/document/d/1WK673QArNxdJi-JSf2J30GhmNk45gyYF2WCPLfzE8a8/edit#heading=h.9s45exk8c5x4

**Comment by jkarpen** [comment]
Slides with markdown info: https://docs.google.com/presentation/d/1_qY5uI9w6qL_DSVq1t1V80crJNDn3ZkagrMfb0YNC_Y/edit#slide=id.gd01156d741_1_3

**Comment by tnrahim** [comment]
Make the changes here ->https://github.com/cagov/data-infrastructure/tree/main/docs
To show up here -> https://cagov.github.io/data-infrastructure/

Create Git Hub Section
Create Project Management Subsection
Create Data Engineering Subsection
