### ISSUE TITLE
Okta Integration Phase 2 (Troubleshooting): Troubleshoot CDTFA login errors after Okta Integration

### ISSUE THREAD

**Issue by melanie-logan** [cagov/data-infrastructure#285]
Adding an issue here to document an error encountered after the initial production integration with Okta.

- We experienced an issue where Arman was unable to login using SSO despite correct config and user name assignment. 
- Local login using the updated username worked as expected.

**The issue encountered is below**:

![Screenshot 2024-02-26 at 2 04 15 PM](https://github.com/cagov/data-infrastructure/assets/150380765/6fc31ea4-a4a2-4f52-accc-c9ecba018743)

----------------------------
**Solution:**

After searching online, the following [comminity post ](https://community.snowflake.com/s/article/Solution-to-Error-occurred-in-authorization-OAuth-client-integration-with-the-given-client-id-is-not-found) outlined potential solutions.

The issue was resolved by replacing the snowflake "shortened url" format with the "account locator" or "full url" format.

Original (shortened) url format:
`https://<account_locator>.snowflakecomputing.com`

Replaced with account locator (full) url format:
`https://<account_locator>.<region>.snowflakecomputing.com`

We suspect this issue because the Okta application for this account was defined using the full url prefix specification (e.g., 
exb17208.us-east-1)

`https://exb17208.us-east-1.snowflakecomputing.com`

----------------------------

**Updated values:**
The original integration parameters were defined as:
`
SAML2_SNOWFLAKE_ACS_URL = 'https://vsb79059-aae-cdtfa-return.snowflakecomputing.com/fed/login'
SAML2_SNOWFLAKE_ISSUER_URL = 'https://vsb79059-aae-cdtfa-return.snowflakecomputing.com';
`

Parameters updated to:
`
SAML2_SNOWFLAKE_ACS_URL = 'https://exb17208.us-east-1.snowflakecomputing.com/fed/login'
SAML2_SNOWFLAKE_ISSUER_URL = 'https://exb17208.us-east-1.snowflakecomputing.com';
`

**Comment by ian-r-rose** [comment]
Yeah, I've found that with most tools you need the cloud+region in the locator (if it exists) in order to connect properly. Most of the connections are HTTPS/TLS based on the account URL, so it's really not doing anything tricky, just constructing the URL of the account that we all log into.

**Comment by melanie-logan** [comment]
Good to know!

**Comment by ian-r-rose** [comment]
I'd love to have a better understanding of when the account identifier is expected to work vs when the locator-with-cloud-and-region is needed. [These docs](https://docs.snowflake.com/en/user-guide/admin-account-identifier) indicate that the locator is effectively deprecated, but I've found it's still needed in a lot of places like this. Do you have any insight into that @melanie-logan?

**Comment by melanie-logan** [comment]
Defiantly want to do some research here. I'll let you know what I find!
