### ISSUE TITLE
Add Sentinel service user to remaining snowflake accounts

### ISSUE THREAD

**Issue by melanie-logan** [cagov/data-infrastructure#286]
Creating an issue for adding sentinel service users to our remaining Snowflake accounts for IT hand-off.

Service users needed:
- [x] [CARB](https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/93)
- [x] [Caltrans](https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/93)
- [x]  CDSS

Service user credentials created:

- [x] Main/parent account
- [x] Sandbox account
- [x] CDTFA
- [x] Caltrans
- [x] CARB
- [x] CDSS

**Comment by ian-r-rose** [comment]
Closing as complete
