### ISSUE TITLE
Set up automated Calendly workflow for Office Hours meetings

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#288]
From Jason via Slack:
Is there someone that can take on setting up an automated workflow in calendly to send an email after signup that includes additional instructions on how to make the best of the office hours meeting? Custom workflows are set up here: https://calendly.com/app/workflows/team/337490
What needs to happen is:

1. Draft an email that includes brief instructions on things to come prepared with during office hours for MDSA and DSA (can tap Esa for content on DSA)
2. Create workflow and copy the finalized email over to the configuration, setup workflows here for the CalData team: https://calendly.com/app/workflows/team/337490
3. Test to make sure it works (on a fake event type first, then apply to the ODI Data Services Office Hours)

**Comment by jasonlally** [comment]
@britt-allen - thanks for picking this up! Worst case we can have Esa draft up something for DSA on Monday if Kim doesn't have time. I think we can structure it into 2 sections to keep it easy and just some bullet points of what to come prepared to discuss for each of the services.

**Comment by britt-allen** [comment]
Sent a draft to Kim and Jason, awaiting their review/feedback/approval. May need to wait til Monday to get DSA content from Esa.

**Comment by britt-allen** [comment]
https://calendly.com/app/workflows/team/337490

**Comment by britt-allen** [comment]
@jasonlally both Esa and Kim are OOO today, shall we continue holding off on this or is what I drafted good to go?

**Comment by jasonlally** [comment]
Yeah we can wait until tomorrow
