### ISSUE TITLE
Develop and send the follow up survey

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#292]
Develop and send the follow up survey to go to [all respondents that signed up for user research](https://airtable.com/appcEMEDxEUtPem12/tblc0sVnj17lHA90h/viwt8L2Uy3nYq4kLA?blocks=hide)

give a deadline schedule a reminder or two

**Comment by britt-allen** [comment]
This is ready for review and feedback: https://forms.gle/GN5hYWFf1dufJ4d8A @ian-r-rose @jasonlally @jkarpen

**Comment by britt-allen** [comment]
temporarily assigning reviewers so they can track this

**Comment by britt-allen** [comment]
I will send this out on Friday morning. If you'd like to review please do so before then.

**Comment by jkarpen** [comment]
@britt-allen I might change the first question from "What department or agency are you at?" to "What department or agency are you with?"

I would also rephrase the question "How do our current data assets fall short in meeting your team's needs?" to something like "Do our current data assets meet your needs? If not, how can they be improved?" 

Other than that I think the rest are good!

**Comment by britt-allen** [comment]
Thank you, Josh! These revisions are helpful!

**Comment by jkarpen** [comment]
Next steps:

- [ ] Send out survey in sprint 2024-07
- [ ] Give 1 week for people to respond (Britt will send a remind on day 4 or 5)
- [ ] Review results (Britt/Ian/Jason)

**Comment by britt-allen** [comment]
AAE sample - https://docs.google.com/forms/d/e/1FAIpQLScRi4wxyf_cKm52kaSUEv6qK9QrOuI12710w3TOAgKUqYQebg/viewform

**Comment by ian-r-rose** [comment]
I agree with Josh's suggestions above. A few additional notes:

* Instead of "How would an updated or enriched building footprint dataset impact your work and therefore Californians?", perhaps just "Would an enriched building footprint dataset impact your work for the State?"
* Maybe note in the introduction that we also partition them by county?
* "What are you looking for?" feels a little open ended for a multiple choice question. What about something like "What would make your work with building footprint data easier?"

**Comment by britt-allen** [comment]
I worry that the rewording of "How would an updated or enriched building footprint dataset impact your work and therefore Californians?" to "Would an enriched building footprint dataset impact your work for the State?" would only elicit yes or no answers, but I want context. I think the assumption is that it would impact their work and we want to understand how. Wdyt? @ian-r-rose

**Comment by ian-r-rose** [comment]
Sure, that makes sense to me

**Comment by britt-allen** [comment]
Thank you for your feedback @ian-r-rose. I have sent the survey, team.
