### ISSUE TITLE
dbt Coalesce presentation first draft

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#294]
[Draft slides](https://docs.google.com/presentation/d/1Mq4qNgDzmOnTdCuNMtR9g0_Az_ZgSb3zLe2eaDk5uOo/edit#slide=id.g1e73c331b15_0_128) and the [outline that powers the slides](https://docs.google.com/document/d/1ye0KgI0YovI3zxcd8-_1t0B6fkx1Q4sj/edit?pli=1) with feedback and questions from dbt

**Comment by britt-allen** [comment]
I'd love some review on this before Tuesday if possible, I have been drafting everything alone so far and feel a bit stuck. @jkarpen @ian-r-rose @jasonlally

**Comment by ian-r-rose** [comment]
I've blocked off some time for Monday morning to review, thanks for the reminder!

**Comment by britt-allen** [comment]
Thank you Ian 🧡

**Comment by jkarpen** [comment]
@britt-allen I just requested access
