### ISSUE TITLE
Slides for All Staff Meeting

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#300]
From Jason:
_Could you get this started with Ian and Britt’s input as needed and then I can do a review and edits. We can keep it super simple! 
If you want to just include the accomplishments and look ahead I can add in the relationship to strategic ODI goals.
We can discuss at mid sprint as well with the team to align expectations and see if Ian and Britt would like to present on our behalf.
It’s due COB April 11th so if we are mostly done by Tuesday next week I can jump in then and iterate as needed._

Original Request:
_In anticipation of the upcoming All Staff Meeting, we are asking each team within ODI (Operations, Strategy, CalData, and CalInnovate) to create a report-out presentation. 
This presentation should be a high-level presentation including:_

- Reflection: What your team has accomplished in the last quarter (01/2024 - 03/2024) in relation to ODI's strategic goals. 
- Look Ahead: What your team is hoping to accomplish in the next quarter (04/2024 - 06/2024) in relation to ODI's strategic goals. 

_Each team will have 12 minutes to present at the All Staff meeting and will be asked to prepare slides for the presentation. I recommend each team use the [ODI Design Asset](https://coda.io/d/ODI-Design-Assets_dKdczZJgfRh/ODI-Design-Assets_supXk#_lun50) slide templates in developing their presentation. This report-out offers an excellent opportunity to showcase the achievements of each team with all of ODI, demonstrate how each team's work contributes to achieving ODI's goals, and set our intentions for the quarter ahead. Action items for each team and their deadlines are listed below, if you have any additional questions please reach out to me._ 

**Action Items**
- [ ] Complete and submit your team's slides to the [talent inbox](mailto:odi-talent-team@innovation.ca.gov) no later than COB, Thursday, April 11th, 2024. 
- [ ] Identify your team's presenter(s) and communicate those names to Sam no later than COB, Thursday, April 11th, 2024.

**Comment by jkarpen** [comment]
@jasonlally @britt-allen @ian-r-rose Draft of slides for the ODI All-Staff are [here](https://docs.google.com/presentation/d/1Yf8Zx-43aDU6Vz3W6U0-31NtvgOEj0sc98pYYKypdxA/edit#slide=id.gd01156d741_1_3)

Please provide any feedback (and feel free to add in items I left out or reword things for clarity). They are due end of day tomorrow, 4/11. I left space on slide 5 for additional goals for next quarter. 

Temporarily assigning this issue to you for review.

**Comment by jasonlally** [comment]
@jkarpen - thanks so much for putting this together. Looking good. I added some comments and made some direct edits. 

@britt-allen - on Thursday 4/11, can you prioritize giving this a fresh look with your excellent eye toward design and communication and other feedback. The actual presentation isn't until 4/22 so we can do a walk through and practice before the actual day.

**Comment by britt-allen** [comment]
Yes i blocked off 12-2 pm on my calendar tomorrow to prioritize this!

**Comment by britt-allen** [comment]
All done with my edits @jasonlally @jkarpen

**Comment by jasonlally** [comment]
@britt-allen - thank you for your edits. Team this all looks great and I've sent to talent. I'm hoping we can fit our content with AAE in 12 mins. I didn't realize that was for all of CalData. I'll connect with Kim next week and hopefully its not an issue.

Closing as complete. If we have edits required, I can re-open.
