### ISSUE TITLE
Assess self-service training options with CalAcademy

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#301]
The ask here is to assess whether self-service training is an option for customer agencies in the future, possibly by recording training videos and have pdf content available to supplement.

Brainstorm with Annie and Amy. 

This is a follow-on task from the MDSA retro the team held in March.

**Comment by jkarpen** [comment]
@britt-allen added this to next sprint as a possible task, but let me know if you think it should be held in the backlog.

**Comment by jkarpen** [comment]
@britt-allen when you have a chance could you put a size estimate on this one? Thank you!

**Comment by britt-allen** [comment]
Meeting with Annie scheduled for Mon 10/14

**Comment by ian-r-rose** [comment]
@britt-allen do you have anything from this assessment that you can add here?

**Comment by britt-allen** [comment]
Yes, after my meeting with Annie which I documented [here](https://docs.google.com/document/d/1Aef5fa4vdjcJMfEJQS2FTu9WdcyyQKTfDNtM6qbnIBc/edit?usp=sharing) we discussed collaborating/experimenting with Google classroom as a platform for self-service training. I created #408 as a next step.
