### ISSUE TITLE
MDSA Retro Follow-on: Develop new applicant briefing doc

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#305]
Create a document for tracking important details about new MDSA applicants. Josh will create a template with headers and run by Jason and Ian for review. 

Notes from Retro sticky notes:

**Develop process for identifying baseline client technologies**
could be something project champion helps us with
github desktop works (so far)
powershell is sometimes locked down
git bash is sometimes not locked down but sometimes people cannot connect to GitHub

Make sure this includes some section on tools to identify what (if any) tools the applicant already has in place? Any they do not have will need to be procured so we want to loop them in early on it
This could be a simple table of tools and whether they have it or not

**Be much more explicit about data access needs and in-scope datasets during project selection and development.**

**Staff requirements**
Require staff to have prior knowledge of working with the project data
or 
Advanced SQL/Data modeling knowledge
these can be yellow flags for project selection

**Comment by jkarpen** [comment]
@ian-r-rose Would you consider this issue completed by the doc you created here? https://docs.google.com/document/d/1_pVzaPbSb28doC7L8zeRZfuFFFuut6APSRe5Swv1oB0/edit?pli=1#heading=h.rtlst0j4o648

**Comment by ian-r-rose** [comment]
Yes, I think so, thanks for the flag!
