### ISSUE TITLE
Draft response to Topher Buck (DTSC)

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#312]
Draft response to DTSC in this doc: https://docs.google.com/document/d/1RjT-ZScDXQv59X1XaQ1x1gs0pgSdbM-6QnyOt5q_o5I/edit

- [x] @ian-r-rose  will fill in reproducible research best practices section
- [x] @tnrahim  will fill in section on data governance at DTSC

Aim to be ready to send out by 4/17.

**Comment by ian-r-rose** [comment]
Closing as complete
