### ISSUE TITLE
Create narrative description of handoff steps in project docs

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#323]
Per our meeting on 6/27/24 (notes [here](https://docs.google.com/document/d/1r37Eu5Vt2pMfw4ePcuEjyx_LsavdmZViW3jMzDuDJpE/edit)), the ask here is to writeup a narrative description of some of the steps in these handoff checklists:
CalHR: https://docs.google.com/spreadsheets/d/1YRBzOH9wS-CgqCq6P8aPNy6Yu-KjHigOPmweAcmX79s/edit?gid=0#gid=0
CARB: https://docs.google.com/spreadsheets/d/1KP1JlbWmq4B5ItqrRTqmGbNJFfhPl2IwJge_H9P-9rU/edit?gid=0#gid=0
 
This can happen after Caltrans project ends during our documentation/cleanup period.

Note: write up the narrative descriptions within Coda along with the handoff checklist.

**Comment by ian-r-rose** [comment]
A note while I'm thinking of it: we should capture any infrastructure costs as part of our hand-off for posterity. It's possible to _loose_ some of the information during the hand-off if accounts are transferred, or if we look back after cost retention windows.

**Comment by jkarpen** [comment]
@ian-r-rose I added a step for each of the platforms in the checklist reminding to create a snapshot of infrastructure cost data before the account transfer (per your comment above). Here is the link to the checklist: https://coda.io/d/Data-Services-Engineering_dY5Oul8-jdi/Handoff-Planning-Checklist_suBgCriF#Handoff-Checklist-Template_tuS56cAZ

As we discussed in 1:1 a while back, I also added narrative to the top of the page explaining how to make use of the checklist and a reminder that the steps do not need to happen in sequence. Can you take a look and let me know if you would add anything to that?

**Comment by jkarpen** [comment]
Reviewed with Ian, closing as done.
