### ISSUE TITLE
Create document to gather information from Cohort 2 orgs

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#329]
Goal is to create a document that can be shared with the Cohort 2 orgs to start gathering preliminary information to inform project planning. 

- Timelines
- Staffing
  - Who is available?
  - Hiring considerations
  - Technical background (familiarity with git, SQL, python, R)
- Data sources
  - Type
  - Approx size
  - Approx business
  - Data sensitivity?
  - Firewall considerations?

**Comment by jkarpen** [comment]
@ian-r-rose first draft of the document is available here. Please review when you have the chance. We can talk about it in 1:1 too.

**Comment by ian-r-rose** [comment]
Thanks!

**Comment by jkarpen** [comment]
Ian has reviewed and I have made changes based on his recommendations. Closing this issue, will open a new one if additional updates are needed.
