### ISSUE TITLE
Onboarding Step 0: Get access to systems

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#334]
- [x] 1. GitHub (IT-Ops can invite to the org)
- [x] 2. dbt Cloud (Ian, Britt, or Jason should be able to send invite)
- [x] 3. Active Snowflake accounts (we will need to open a ticket with IT-Ops to assign in Okta)
      a. [Default account](https://heb41095.snowflakecomputing.com/)
      b. [Caltrans](https://ngb13288.snowflakecomputing.com/)
- [x] 4. AWS (Ian can provide access, this one is not urgent and can wait)
- [x] 5. Fivetran (Ian, Britt, or Jason should be able to send invite, this one is not urgent and can wait)

The main GitHub repository for the Data Services and Engineering team is [here](https://github.com/cagov/data-infrastructure). It is a monorepo consisting of a dbt project, terraform configurations, data ingest scripts, and documentation. Most of our project work is in separate repositories and separate Snowflake accounts, so the data-infrastructure repository serves as a reference repository, and contains non-sensitive, non-critical data pipelines.

**Comment by summer-mothwood** [comment]
@britt-allen @jasonlally I think I could use some help gaining access to dbt Cloud and Snowflake (and AWS and Fivetran, though I can wait a few days for Ian to help with those if need be!)

**Comment by britt-allen** [comment]
Confirming @summer-mothwood has access to Caltrans and ODI Snowflake, Fivetran, and Caltrans dbt (there is an issue with ODI dbt I am working on)

**Comment by summer-mothwood** [comment]
thank you @britt-allen !!!

**Comment by britt-allen** [comment]
ticket for State of California - ODI dbt cloud access: https://airtable.com/app1Jm2SLJEU3ljBr/pagUUMkYMw6S6Gg5n?detail=eyJwYWdlSWQiOiJwYWdRM3BIZWQ4eXdYd2VNRiIsInJvd0lkIjoicmVjT3hqTFJ1TUFXYjFrdjEiLCJzaG93Q29tbWVudHMiOmZhbHNlLCJxdWVyeU9yaWdpbkhpbnQiOm51bGx9

**Comment by summer-mothwood** [comment]
@ian-r-rose the only thing left here is AWS access, which I think I need your help with -- noted that it's not urgent, though!

**Comment by ian-r-rose** [comment]
@summer-mothwood feel free to grab 15 minutes on my calendar and we can get you AWS access!
