### ISSUE TITLE
Onboarding Step 2: Set up development environments

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#336]
- [x] Install software for managing Python virtual environments. Most of the team uses [Anaconda](https://anaconda.org/), and much of our documentation references that. But if you like alternative approaches (like pyenv), that’s perfectly fine!
- [x] Set up your preferred code editor. Many people like VS Code, but use whatever you are comfortable with.
- [x] Ensure you have git installed on your local machine.
- [x] Follow the [instructions](https://cagov.github.io/data-infrastructure/code/local-setup/) in the data-infrastructure repository to set up a local development environment for that repository.
- [x] Follow the [instructions](https://cagov.github.io/caldata-mdsa-caltrans-pems/setup/) in the Caltrans repository to set up a local development environment for that repository. This should be almost identical to the instructions for the data-infrastructure repository (by design)!.

**Comment by summer-mothwood** [comment]
tons of questions about the documentation for setting up the local dev environment, captured those questions in my onboarding projects doc, and going to go over them with Ian tomorrow
