### ISSUE TITLE
Improve information architecture of our docs

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#347]
Does the current structure of pages make sense right now? Probably not, it accreted over time, without much thought to what a sensible organization might be. A lot of the names of subpages are confusing, and relevant information on similar topics is scattered across a number of different pages. For instance, information about setting up Snowflake can be found [here](https://cagov.github.io/data-infrastructure/setup/#configure-snowflake), [here](https://cagov.github.io/data-infrastructure/snowflake/), and [here](https://cagov.github.io/data-infrastructure/dbt/).

Let's think about how we can reorganize the pages and the content therein to make it easier to navigate.

**Comment by jkarpen** [comment]
@JamesSLogan will drive this one but can reach out to @britt-allen for review.
