### ISSUE TITLE
Troubleshooting Support on Pre-commit check

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#349]
Email from Andrew for support:

"Mike (cc’ed) as a branch whose pre-commit CI job keeps failing, without very informative errors. I have spent some time on it and can’t make sense of what is going on. Can you please put Mike in touch with the best person at ODI to help us debug? Thanks in advance,"

**Comment by jkarpen** [comment]
Taheer will meet with Mike on 8/19 or 8/20.

**Comment by britt-allen** [comment]
This may help: https://github.com/cagov/caldata-mdsa-caltrans-pems/issues/220 and https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/246 @tnrahim

**Comment by tnrahim** [comment]
@britt-allen Thank you for the links! They were both super helpful. Updating SQLfluff resolved the issue.
