### ISSUE TITLE
Check MDSA survey results / follow-up

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#357]
Ask is to check on MDSA [survey results](https://docs.google.com/forms/d/1AUzs3wWgG6D-YrVCBksM9uwJNKPJvRSdUB59AjtAZ2w/edit#responses) and follow-up with non-responders. 

Take a first pass at analyzing the results, then schedule a session with the team to review together with whole team (incl Analytica). 

Results summarized [here](https://docs.google.com/document/d/16KQYKoBEPF1SY6zVjMJrMrcNf8AlwTzVfsWBSDTMECw/edit)

**Comment by jkarpen** [comment]
@jkarpen will schedule the review session for early next week (week of 9/9)

**Comment by britt-allen** [comment]
@jkarpen can you schedule this for tomorrow or Wednesday please?
