### ISSUE TITLE
Update dbt set up docs to include Snowflake OAuth

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#365]
We want to link [the docs for dbt Snowflake OAuth](https://docs.getdbt.com/docs/cloud/manage-access/set-up-snowflake-oauth) to [this page](https://cagov.github.io/data-infrastructure/setup/dbt-setup/) (maybe step 4)

**Comment by jkarpen** [comment]
@ian-r-rose flagging for you to review since we did not get to this in backlog cleanup due to time.

**Comment by ian-r-rose** [comment]
We already have been using Snowflake OAuth for most of our dbt Cloud projects (this is where you get a Snowflake login screen in the dbt Cloud IDE). It's currently not very well documented, but there are steps for it in our handoff checklist.

**Comment by britt-allen** [comment]
Change step 4 here: https://cagov.github.io/data-infrastructure/setup/dbt-setup/

These docs will be helpful: https://docs.getdbt.com/docs/cloud/manage-access/set-up-snowflake-oauth
