### ISSUE TITLE
Explore Azure Devops and dbt Cloud integration

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#368]
The CalHFA team uses Azure DevOps so this will help us prepare for our engagement with them as they'd prefer not to use GitHub

**Comment by britt-allen** [comment]
A helpful link for myself: https://docs.getdbt.com/docs/cloud/git/connect-azure-devops

**Comment by britt-allen** [comment]
From Ian: It will require us to get access to DevOps. In theory we have an Azure sandbox account now, but I haven’t gotten it working yet. So part of this issue would actually be to work with IT to resolve whatever issue is preventing us from using it.

**Comment by ian-r-rose** [comment]
I'm going to close this in favor of https://github.com/cagov/caldata-dse-internal-tracker/issues/18 and https://github.com/cagov/caldata-dse-internal-tracker/issues/19, which are a bit more granular and part of a larger milestone around setting up DevOps
