### ISSUE TITLE
Onboarding Step 0: Get access to systems

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#369]
1. GitHub (IT-Ops can invite to the org)

2. dbt Cloud (Ian, Britt, or Jason should be able to send invite)

3. Active Snowflake accounts (we will need to open a ticket with IT-Ops to assign in Okta)
a. [Default account](https://heb41095.snowflakecomputing.com/)
b. [Caltrans](https://ngb13288.snowflakecomputing.com/)
c. [CDSS](https://gc94702.west-us-2.azure.snowflakecomputing.com/console/login#/) (to be deleted 10/1)
d. [CDTFA](https://app.snowflake.com/vsb79059/aae_cdtfa_return/worksheets)

4. AWS (Ian can provide access, this one is not urgent and can wait)

5. Fivetran (Ian, Britt, or Jason should be able to send invite, this one is not urgent and can wait)
The main GitHub repository for the Data Services and Engineering team is [here](https://github.com/cagov/data-infrastructure). It is a monorepo consisting of a dbt project, terraform configurations, data ingest scripts, and documentation. Most of our project work is in separate repositories and separate Snowflake accounts, so the data-infrastructure repository serves as a reference repository, and contains non-sensitive, non-critical data pipelines.

**Comment by jkarpen** [comment]
fixes #370

**Comment by ram-kishore-odi** [comment]
I would not need access to CDSS account as per Jason.
For AWS access, I will need to work with Ian after he is back.

Got access to Snowflake, Github, dbtCloud and Fivetran.

**Comment by britt-allen** [comment]
ticket for State of California - ODI dbt cloud access: https://airtable.com/app1Jm2SLJEU3ljBr/pagUUMkYMw6S6Gg5n?detail=eyJwYWdlSWQiOiJwYWdRM3BIZWQ4eXdYd2VNRiIsInJvd0lkIjoicmVjT3hqTFJ1TUFXYjFrdjEiLCJzaG93Q29tbWVudHMiOmZhbHNlLCJxdWVyeU9yaWdpbkhpbnQiOm51bGx9

**Comment by britt-allen** [comment]
Confirming @ram-kishore-odi has access to Caltrans and ODI Snowflake, Fivetran, and Caltrans dbt (there is an issue with ODI dbt being worked on)
