### ISSUE TITLE
Onboarding Step 2: Set up development environments

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#371]
- [ ] Install software for managing Python virtual environments. Most of the team uses [Anaconda](https://anaconda.org/), and much of our documentation references that. But if you like alternative approaches (like pyenv), that’s perfectly fine!
- [ ] Set up your preferred code editor. Many people like VS Code, but use whatever you are comfortable with.
- [ ] Ensure you have git installed on your local machine.
- [ ] Follow the [instructions](https://cagov.github.io/data-infrastructure/local-setup/) in the data-infrastructure repository to set up a local development environment for that repository.
- [ ] Follow the [instructions](https://cagov.github.io/caldata-mdsa-caltrans-pems/setup/) in the Caltrans repository to set up a local development environment for that repository. This should be almost identical to the instructions for the data-infrastructure repository (by design)!.

**Comment by ram-kishore-odi** [comment]
Updated the instructions link for the data-infrastructure repository above to the correct one in the onboarding documentation for future reference.

**Comment by ram-kishore-odi** [comment]
Installed all the required software and setup the config as defined in the story. 

I plan to do the end to end validation that everything is in place after Ian meeting on Friday probably using some sample data.
