### ISSUE TITLE
Improve Snowflake Security Step 1: Security Improvements

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#375]
1. Read email sent from Gabe Mullen, Snowflake rep, providing context for security changes: [Snowflake Security Best Practices Email](https://docs.google.com/document/d/115NjREC27uGy7EIjSFJZRL6BvPdO_opWuLT7l6RNjJc/edit)
2. Review [guidance from Snowflake](https://www.snowflake.com/en/resources/white-paper/best-practices-to-mitigate-the-risk-of-credential-compromise/) on how to improve security.
3. Review [Trust Center documentation](https://docs.snowflake.com/en/user-guide/ui-trust-center):
4. The team met with Gabe on 8/28. Most of the call was about data caching best practices but this topic came up towards the end of the call and Gabe provided some guidance. You may want to watch the whole call as data caching will likely be relevant to you in the future. 
         a. [Zoom recording](https://innovation-ca.zoom.us/rec/share/pDtiM3NRhpj7rw7TNZmfwVBVA7DLkqO_Pk6-vkKSde1fFoEFuFVp4osGlpj3l2Gy.s-d6EfR3Fyi9eogg) (Passcode:r5A?82Vm )
          b. Meeting notes: [Notes - Snowflake Data Caching Best Practices (https://docs.google.com/document/d/12klynFZhlrYQuGVtd5TeMeHazd26KDFOw1jhhoGFqPQ/edit?pli=1)
           c. If needed we can schedule a follow-up call with Gabe to answer any specific questions not answered in the documentation/Zoom recording.
5. Recommend necessary changes based on these recommendations. 
6. Implement changes (can wait until Ian returns)

**Comment by ian-r-rose** [comment]
Can you say more about what you think we should do on RBAC? We do already have an RBAC setup that I believe conforms to the recommendations in Snowflake's docs.

**Comment by ram-kishore-odi** [comment]
Hello @ian-r-rose, My intention was to do a deep dive on the existing RABC setup using best practices defined in this article, https://articles.analytics.today/snowflake-role-based-access-best-practices-design-guide, and see if we can take advantage of items shown below.  

I'm particularly interested in exploring these areas for potential improvement:

**Managed Access Schemas**: using managed access schemas to prevent table owners from granting access to unauthorized roles.
**Role Hierarchy Optimization**: Streamlining our role structure for clearer access control and easier management.
**Simplified RBAC management** and OKTA User Provisioning :  To reducing manual effort and risk. For example, working Kevin to over come automated provisioning / de-provisioning issues. The goal is to have a well defined process for role assignment and provisioning for new users 

These are some of my thoughts, please let me know your feedback

**Comment by ian-r-rose** [comment]
I'd be very interested in taking a closer look at managed access schemas and whether we can use that to improve the security of our default setup. One wrinkle to this is that many of our schemas are created by dbt as part of the transformation step. As far as I know, dbt cannot create managed access schemas (cf https://github.com/dbt-labs/dbt-snowflake/issues/22) without overriding the schema creation macros. This may be worthwhile, but I think I'd like to better understand the tradeoffs:

1. Right now with our default RBAC setup, the owner of most objects is `{database}_{env}_READWRITECONTROL`. This goes for both schemas and for tables/views in schemas. If there is no difference between the owner of the schema and a table in the schema, is there any benefit to making the schema managed access?
2. Can managed access schemas help simplify the way we do future grants? If the schema owner already gets some variety of permissions on objects in them, maybe they can be used to remove some of our explicit future grants. Or maybe not, I don't think I fully understand the permissions model here.

**Comment by ram-kishore-odi** [comment]
Summary of key next steps are show below. Appropriate new stories will be added. This ticket will be closed as the next steps have been defined

1. Security improvements section above is not applicable considering ODI setup/architecture 
2. Add a story for - Setting up fully automated Okta User provisioning and de-provisioning of user accounts - **This already exists** - https://github.com/orgs/cagov/projects/31/views/39?sliceBy%5Bvalue%5D=ram-kishore-odi&pane=issue&itemId=38008492&issue=cagov%7Cdata-infrastructure%7C197. This story will be updated to add additional details
3. Added a story for - Future grants simplification using managed access schemas 
4. Added a story for - Evaluate the limitations of DBT's inability to create managed access schemas without overriding macros and ascertain the next steps
