### ISSUE TITLE
Improve Snowflake Security Step 2: Review best practices for big data in dbt and Snowflake

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#376]
Big Data resources:
The PeMS project works on some moderately large datasets, and as such, we need to take some special approaches to working effectively with the tables. The following resources are helpful to have digested when working on this project:

- [Configure incremental models | dbt Developer Hub](https://docs.getdbt.com/docs/build/incremental-models) - How to work with incremental models in dbt
- [Clone incremental models as the first step of your CI job | dbt Developer Hub](https://docs.getdbt.com/best-practices/clone-incremental-models) - Cloning incremental models in dbt
- [Defer | dbt Developer Hub](https://docs.getdbt.com/reference/node-selection/defer) - Using deferral in dbt
- [Micro-partitions & Data Clustering | Snowflake Documentation](https://docs.snowflake.com/en/user-guide/tables-clustering-micropartitions) - Snowflake docs on working with micropartitions and clustering. Important for understanding Snowflake query performance.

**Comment by ram-kishore-odi** [comment]
Thank you @jkarpen 

Yes these are very helpful resources. I reviewed the documentation above.
More stories will need to be added on a case by case basis for processing the large data sets and working effectively with the tables. This can be discussed further during the planning sessions as needed
