### ISSUE TITLE
Refine our Snowflake training content and exercises

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#381]
day 1 can use editing for length

- [ ] [Content](https://docs.google.com/document/d/10x82_50s7VH6D62FAkiNTn6s-zu9v7GOBGQFB2K3T68/edit#heading=h.pvig6r2qq8bd)
- [ ] [Exercises](https://drive.google.com/file/d/1NeqWbsMCVkAW1hdak7uElsD2RIjWXdOP/view?usp=sharing)

**Comment by jkarpen** [comment]
@summer-mothwood will drive this with review from @britt-allen. Goal is to complete before we do next training with CalHFA.

**Comment by britt-allen** [comment]
Keep an eye out for any references of GitHub and update to Azure DevOps accordingly
