### ISSUE TITLE
Investigate notifications to a group when nightly job fails

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#393]
Email from Andrew came in asking about the ability to send a notification to a group of dbt devs when the nightly job fails. CARB is using dbt core instead of cloud so they are relying on GitHub actions. Currently only the person who submitted the last PR is receiving the notification. 

The goal for this issue is to investigate whether and how this is possible (notifying a group when the nightly job fails). 

Relevant Doc: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications

**Comment by ram-kishore-odi** [comment]
Hi @jkarpen @ian-r-rose @britt-allen @summer-mothwood 

Can you please review the following document and let me know if you have any feedback before we send it to Andrew ?

https://docs.google.com/document/d/1K8L-lci-0AjuPzbviANYS6lTXgtzUY7QEsAfKeuupps/edit?usp=drive_link

**Comment by ian-r-rose** [comment]
@ram-kishore-odi apologies for the extremely slow review! This looks great, and I think we can send it to the CARB team as-is. I'm happy to send it and CC you if you like, or if you want to do it that works as well.

There are a few things that they probably can't do as-written (they don't have gmail, and can't use third-party actions), but I think that's okay, the approaches here should be adaptable to any of a number of situations

**Comment by ram-kishore-odi** [comment]
@ian-r-rose  No problem at all ! thank you for reviewing the document and sharing your feedback. I have updated the document based to add an additional note to address your comments which are all very valid in my view.

I think it will be better for you to share it with the CARB team. Please go ahead.

**Comment by ian-r-rose** [comment]
Closing as complete, thanks @ram-kishore-odi
