### ISSUE TITLE
Investigate orchestration options

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#4]
We intend to do most transformation in our data warehouse(s) via dbt, but there is still need for scheduled loads of custom data. So while a full DAG framework might be overkill at this point, some sort of workflow orchestration tool is worthwhile.

Some requirements:

1. Execute arbitrary Python, bash scripts
2. User-interface for viewing scheduled runs, failures, metadata
3. Notifications upon failures
4. Retries
5. encrypted secrets

Nice-to-have:

1. Execute R scripts
2. Python virtualenv isolation
3. Managed option (I don't want to personally keep some servers up)

**Comment by jasonlally** [comment]
This is relevant to @melanie-logan working on loading options. 

@ian-r-rose should we close this since Melanie is working on evaluation now?

**Comment by ian-r-rose** [comment]
Makes sense to me!

**Comment by melanie-logan** [comment]
Yes, I can do a separate orchestration Eval. Thanks!

**Comment by ram-kishore-odi** [comment]
Closing this as complete for now. We may revisit orchestration options at some point, but would probably start with a new set of tasks that are relevant. Please refer to this ticket for additional information - https://github.com/cagov/data-infrastructure/issues/378
