### ISSUE TITLE
Investigate failing building footprints loader DAG

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#403]
Following up on #391 , the building footprints DAG is still failing. Let's figure out why and fix it.

**Comment by ram-kishore-odi** [comment]
The job is failing due to the dependencies between fiona and geopandas python modules being used by the loaded DAG
One option to fix is to pin the dependencies -  fiona and geopandas

**Comment by ram-kishore-odi** [comment]
The job ran as expected this time and did not encounter any loading failures. Please see addition details below

Batch Job
https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#jobs/fargate/detail/2bc123b3-f98a-496e-b1b5-5b1c2fb9d45f

Log
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/%2Faws%2Fbatch%2Fjob/log-events/dse-infra-dev-us-west-2-test%2Fdefault%2Fe1b9753b5adc45128d2451f816b2b535


Changes have been already been merged into main by Ian.
