### ISSUE TITLE
Upgrade to dbt Versionless

### ISSUE THREAD

**Issue by summer-mothwood** [cagov/data-infrastructure#423]
We want to upgrade our dbt Cloud projects to start using dbt Versionless. Here is my write up on the changes we should be aware of from dbt 1.7 to the current state of Versionless, and what to expect w/r/t adapting to new changes in Versionless moving forward: https://docs.google.com/document/d/1klIhkavJX8ljictkFLgvddsEKZNQX_m_b7kqpapUfqc/edit?usp=sharing 

Luckily the upgrade itself should be relatively low-lift -- there are very few configuration or syntax changes that are likely to break anything in our current set ups. With that in mind, here is the plan for upgrading:

This sprint:
1. Upgrade Dev env in DSE Infrastructure project
2. Test and observe new features
3. Upgrade Prd env in DSE infrastructure project
4. test and observe new features

Next sprint:
1. Upgrade Dev env in Caltrans project and inform Caltrans team
2. Test and observe new features, incl. microbatching
3. (If all goes well) Upgrade Prd env in Caltrans project
4. test and observe new features

**Comment by summer-mothwood** [comment]
@ram-kishore-odi  I don't seem to have developer access to the ODI Snowflake account. The only role I have access to is Public, is this something I can ask your help on? ![Image](https://github.com/user-attachments/assets/a09b6991-038e-45c1-a389-4061c31fcc01)

**Comment by ram-kishore-odi** [comment]
Hi @summer-mothwood, You should now have developer access ! Please let me know if you encounter any issues.

**Comment by summer-mothwood** [comment]
@ram-kishore-odi Hey Ram! I can now view data in the ODI snowflake account in both Snowflake and dbt Cloud, so I was able to succesfully view and make edits to the repo in both Snowflake and dbt Cloud. But there still seems to be something off with my permissions in Snowflake, because I can't create a new schema to _run_ any code while in dbt Cloud:

![Image](https://github.com/user-attachments/assets/aaf9983f-0cd6-4575-bf66-7447e293c655)

cc @britt-allen

**Comment by ian-r-rose** [comment]
`TRANSFORMER_DEV` already has access to `CREATE SCHEMA` in `TRANSFORM_DEV`, so the issue is likely something else: https://github.com/cagov/data-infrastructure/blob/ebd59ff8c5559a54b19fa90488219ed65e2ad6e2/terraform/snowflake/modules/database/main.tf#L42

Not sure what the problem is just yet, @summer-mothwood would you be able to do a quick screenshare?

**Comment by summer-mothwood** [comment]
It looks like that second issue might be the real issue then -- needing access to RAW_PRD. TRANSFORMER_DEV does not have any read access to that database, and it's trying to access it when I run any of the models. The env variables I have set up look like this -- should I go ahead and change that RAW_PRD to RAW_DEV, or should we give TRANSFORMER_DEV read access to RAW_PRD?

<img width="655" alt="image" src="https://github.com/user-attachments/assets/1d3dec9f-89bf-4929-ae61-88412cbe0603">

**Comment by ian-r-rose** [comment]
Yes, that is almost certainly the issue! In some of the terraform work, the grant to production data was lost. There is documentation of how it is set up and what the appropriate grant should be [here](https://cagov.github.io/data-infrastructure/setup/snowflake-setup/#developing-against-production-data)

**Comment by ram-kishore-odi** [comment]
Hi @ian-r-rose, The link in your comment is suggesting that the RAW_PRD_READ TO ROLE TRANSFORMER_DEV grant is managed outside of terraform. Unless it is explicitly granted after the terraform upgrade, it is not going to be present.
Can you please let me know if I am missing anything here ?

**Comment by ian-r-rose** [comment]
The reason it was lost in the terraform upgrade is that the `TRANSFORMER_DEV` role was accidentally destroyed and recreated. When we take the path of migrating the terraform state using `rm`/`import`, the grant should be maintained.

I agree, no action is required in the terraform configuration (unless we want to move this grant into the configuration!).

**Comment by ram-kishore-odi** [comment]
Please note that the RAW_PRD_READ has been granted to ROLE TRANSFORMER_DEV in the CalTrans snowflake instance.

**Comment by ian-r-rose** [comment]
@ram-kishore-odi that one should have already been there, the one that was missing was in the main snowflake instance

**Comment by ram-kishore-odi** [comment]
@ian-r-rose Yes, I did it for the main ODI snowflake instance a short while ago. I am about to grant the CREATE FUNCTION' for CalTrans Transformer_Dev on the public schema. Can you please confirm I can go ahead ?

**Comment by ian-r-rose** [comment]
Confirmed!

**Comment by summer-mothwood** [comment]
We got very exciting/interesting news today from our dbt reps that dbt is backpedaling on Versionless somewhat, seemingly from feedback from other customers who would also like to be able to maintain the ability to switch between Core and Cloud seamlessly and/or maintain parity with other non-dbt packages. It hasn't been announced yet, but they outlined how dbt version selection will work in Cloud soon. Basically when you're choosing what version of dbt to use, you'll have 3 options (I don't remember what cute names they had for the 3 versions, but here's what I gathered):

1. "Very Stable" - should align to a version of dbt Core that is maybe 1-2 versions behind current
2. "Compatible with Core" - should align to a version of dbt Core that is recent (maybe the most recent major release?)
3. "Ahead of Core" - aligns with what they're calling Versionless right now -- so, a constantly-updating version of dbt that debuts new features before they're available in dbt Core


I'm going to continue flipping the final switches on the migration to Versionless as we haven't run into any issues yet, but I look forward to seeing this new rollout. I assume we'll opt into either option 1 or 2 for our projects moving forward, depending on what they look like in practice.

**Comment by summer-mothwood** [comment]
All jobs and environments for both the Caldata and Caltrans dbt projects are now in Versionless. Both projects have the new flags we care about turned on/off as appropriate. The Caldata project also has the most pressing syntax changes (renaming 'tests' as 'data_tests' in yaml files) made. I'll be making those changes in the Caltrans project along with a larger issue to _add_ data tests to more of the models in Caltrans.

I also enabled warning notifications for the Nightly builds for myself and I recommend others do too -- a lot of the new features that get pushed to Versionless will give off warnings for a while before they become enabled by default. As long as we are on Versionless, we'll need to keep a close-ish eye on new features, esp new behavior flags, as they're released.
