### ISSUE TITLE
Should we rename our GCP project?

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#74]
We currently have a "prod" GCP project for our CalInnovate called `dse-product-analytics-prd-bqd`.

This doesn't really adhere to our [naming conventions](./docs/naming-conventions.md), both before and after #60: it has a resource-type suffix of `bqd`, for "BigQuery Dataset". But it's not a BigQuery dataset, it's a GCP project.
A naming-convention-consistent project name would drop the resource type: `dse-product-analytics-prd`.

Unfortunately, it's not possible to rename a GCP project, so we'd have to create a new one and migrate resources over to it. This makes it a somewhat painful proposition.

cc @jasonlally and @britt-allen discussion

**Comment by ram-kishore-odi** [comment]
Closing this as not planned. We are not current not focussed on GCP offerings. Please refer to this ticket for additional information - https://github.com/cagov/data-infrastructure/issues/378
